### ISSUE TITLE
Set reference value for color range in viridis

### ISSUE THREAD

**Issue by rafapereirabr** [sjmgarnier/viridis#38]
This is more of a suggestion than an issue. I know viridis package already has `begin` and `end` arguments to set color range.  I think it would be great if it there was also a way to set what point in the variable distribution should be considered as the middle point in the color gradient.

I've posted a [questions about this in SO](http://stackoverflow.com/questions/37905981/set-reference-value-for-color-range-in-viridis-or-rcolorbrewer), but I thought I should leave this suggestions here and thank you for the package.

thanks!

Rafael Pereira

**Comment by sjmgarnier** [comment]
@rafapereirabr Wouldn't this make your scale non perceptually-uniform? It's kind of what viridis is NOT about :-)

**Comment by rafapereirabr** [comment]
Yes, you're correct. The question is that I wanted to keep green and yellowish colors to represent positive values and blue and purpleish colors to represent negative values, but my distribution is not symmetrical.

**Comment by sjmgarnier** [comment]
@rafapereirabr Why don't you just use the `limits` argument to set the range of the scale? In the example in your SO question, making the range of the scale [-0.5;1] should make 0.25 the middle point, no? 

I will close this issue because it's not something that I think we should include given the purpose of these color scales.

**Comment by rafapereirabr** [comment]
No problem :) Thanks for the suggestion.
